[package]
name = "argentum_game"
description = "The Argentum Voxel Engine"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
bevy = "0.14.1"
ndarray = "0.16.0"
quickcheck = "1.0.3"
