name: Code Quality Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Enforce_Code_Quality:

    runs-on: ubuntu-latest

    steps:

      # if it's a regular push
      - name: Checkout repository
        uses: actions/checkout@v4
        if: github.event_name == 'push'
        with:
          # Use CARGO_ASSIST_TOKEN if available, by specifying the PAT secret name.
          # In forks it's not available, so use the default GITHUB_TOKEN.
          token: ${{ secrets.CARGO_ASSIST_TOKEN || secrets.GITHUB_TOKEN}}
          fetch-depth: 0

      # if it's a PR
      - name: Checkout repository
        uses: actions/checkout@v4
        if: github.event_name == 'pull_request'
        with:
          # Use CARGO_ASSIST_TOKEN if available, by specifying the PAT secret name.
          # In forks it's not available, so use the default GITHUB_TOKEN.
          token: ${{ secrets.CARGO_ASSIST_TOKEN || secrets.GITHUB_TOKEN}}
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install dependencies
        run: sudo apt install mold clang pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0

      - name: Enable risky lints
        run: echo "__CARGO_FIX_YOLO=1" >> $GITHUB_ENV
      - name: Run Cargo Assist
        uses: MarcoIeni/cargo-assist@v0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build code & run tests
        run: cargo test --verbose --workspace --exclude argentum_game
