name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Use CARGO_ASSIST_TOKEN if available, by specifying the PAT secret name.
        # In forks it's not available, so use the default GITHUB_TOKEN.
        token: ${{ secrets.CARGO_ASSIST_TOKEN || secrets.GITHUB_TOKEN}}

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Install dependencies
      run: sudo apt install mold clang pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0

    - name: Build code & run tests 
      run: cargo test --verbose
    - name: Run Cargo Assist
      uses: MarcoIeni/cargo-assist@v0.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # <-- To be the author of the commit,
                                                  #     set the PAT secret name here, too.
